Adding suggested extensions and bug fixes
linksplatform/Ranges pull request #61
Opened 2021-07-14 14:59 UTC by uselessgoddess

2021-07-14 15:00 UTC, uselessgoddess commented
#44 #58

2021-07-25 14:46 UTC, Konard requested changes

2021-07-25 14:46 UTC, Konard commented on cpp/Platform.Ranges/EnsureExtensions.h
> +    template <typename TArgument, typename T>
Do we really need second type parameter here?

2021-07-25 14:46 UTC, Konard commented on cpp/Platform.Ranges/Range[T].h
> +        constexpr bool operator==(const Range<TOther>& other) const noexcept
Please move this operator to the previous position (the single line style should be preserved).

2021-07-25 16:01 UTC, merged